### ISSUE TITLE
Docker standalone example

### ISSUE THREAD

**Issue by gilacost** [tombruijn/appsignal-examples#9]
There is not a lot of documentation about this is the standalone agent supposed to collect all logs directly form the stdout when part of composed services in a compose.yaml?

What does "if  configured" mean in this [page](https://docs.appsignal.com/standalone-agent/installation/docker-image.html)?

**Comment by tombruijn** [comment]
Hi @gilacost, please contact us at support@appsignal.com with your question for more help.

This repo is only for showing some example apps, and the repo itself is not actively maintained. I'll archive it actually.

**Comment by gilacost** [comment]
> Hi @gilacost, please contact us at [support@appsignal.com](mailto:support@appsignal.com) with your question for more help.
> 
> This repo is only for showing some example apps, and the repo itself is not actively maintained. I'll archive it actually.

I've already done it! Thanks for the quick response 😄!
